													-- SQL PROJECT --
											--   LIBRARY MANAGEMENT SYSTEM 	 --
                        
CREATE DATABASE MY_PROJECT;
USE MY_PROJECT;

-- TABLE: TBL_PUBLISHER
CREATE TABLE TBL_PUBLISHER (
    PUBLISHER_PUBLISHERNAME VARCHAR(255) PRIMARY KEY,
    PUBLISHER_PUBLISHERADDRESS TEXT,
    PUBLISHER_PUBLISHERPHONE VARCHAR(15)
);

-- TABLE: TBL_BOOK
CREATE TABLE TBL_BOOK (
    BOOK_BOOKID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(255),
    BOOK_PUBLISHERNAME VARCHAR(255),
    FOREIGN KEY (BOOK_PUBLISHERNAME) REFERENCES TBL_PUBLISHER(PUBLISHER_PUBLISHERNAME)
);

-- TABLE: TBL_BOOK_AUTHORS
CREATE TABLE TBL_BOOK_AUTHORS (
    BOOK_AUTHORS_AUTHORID INT PRIMARY KEY AUTO_INCREMENT,
    BOOK_AUTHORS_BOOKID INT,
    BOOK_AUTHORS_AUTHORNAME VARCHAR(255),
    FOREIGN KEY (BOOK_AUTHORS_BOOKID) REFERENCES TBL_BOOK(BOOK_BOOKID)
);

-- TABLE: TBL_LIBRARY_BRANCH
CREATE TABLE TBL_LIBRARY_BRANCH (
    LIBRARY_BRANCH_BRANCHID INT PRIMARY KEY AUTO_INCREMENT,
    LIBRARY_BRANCH_BRANCHNAME VARCHAR(255),
    LIBRARY_BRANCH_BRANCHADDRESS TEXT
);

-- TABLE: TBL_BOOK_COPIES
CREATE TABLE TBL_BOOK_COPIES (
    BOOK_COPIES_COPIESID INT PRIMARY KEY AUTO_INCREMENT,
    BOOK_COPIES_BOOKID INT,
    BOOK_COPIES_BRANCHID INT,
    BOOK_COPIES_NO_OF_COPIES INT,
    FOREIGN KEY (BOOK_COPIES_BOOKID) REFERENCES TBL_BOOK(BOOK_BOOKID),
    FOREIGN KEY (BOOK_COPIES_BRANCHID) REFERENCES TBL_LIBRARY_BRANCH(LIBRARY_BRANCH_BRANCHID)
);
SELECT * FROM TBL_BOOK_COPIES;

-- TABLE: TBL_BORROWER
CREATE TABLE TBL_BORROWER (
    BORROWER_CARDNO INT PRIMARY KEY,
    BORROWER_BORROWERNAME VARCHAR(255),
    BORROWER_BORROWERADDRESS TEXT,
    BORROWER_BORROWERPHONE VARCHAR(15)
);

-- TABLE: TBL_BOOK_LOANS
CREATE TABLE TBL_BOOK_LOANS (
    BOOK_LOANS_LOANSID INT PRIMARY KEY AUTO_INCREMENT,
    BOOK_LOANS_BOOKID INT,
    BOOK_LOANS_BRANCHID INT,
    BOOK_LOANS_CARDNO INT,
    BOOK_LOANS_DATEOUT DATE,
    BOOK_LOANS_DUEDATE DATE,
    FOREIGN KEY (BOOK_LOANS_BOOKID) REFERENCES TBL_BOOK(BOOK_BOOKID),
    FOREIGN KEY (BOOK_LOANS_BRANCHID) REFERENCES TBL_LIBRARY_BRANCH(LIBRARY_BRANCH_BRANCHID),
    FOREIGN KEY (BOOK_LOANS_CARDNO) REFERENCES TBL_BORROWER(BORROWER_CARDNO)
);

																-- TASK QUESTIONS --
                                                                
-- 1. HOW MANY COPIES OF THE BOOK TITLED "THE LOST TRIBE" ARE OWNED BY THE LIBRARY BRANCH WHOSE NAME IS "SHARPSTOWN"?
SELECT BOOK_TITLE,LIBRARY_BRANCH_BRANCHNAME,BOOK_COPIES_NO_OF_COPIES
FROM TBL_BOOK
JOIN TBL_BOOK_COPIES
ON BOOK_BOOKID = BOOK_COPIES_BOOKID
JOIN TBL_LIBRARY_BRANCH
ON BOOK_COPIES_BRANCHID = LIBRARY_BRANCH_BRANCHID
WHERE BOOK_TITLE = "THE LOST TRIBE" AND LIBRARY_BRANCH_BRANCHNAME = "SHARPSTOWN";

-- 2.HOW MANY COPIES OF THE BOOK TITLED "THE LOST TRIBE" ARE OWNED BY EACH LIBRARY BRANCH?
SELECT BOOK_TITLE,LIBRARY_BRANCH_BRANCHNAME,BOOK_COPIES_NO_OF_COPIES
FROM TBL_BOOK
JOIN TBL_BOOK_COPIES
ON BOOK_BOOKID = BOOK_COPIES_BOOKID
JOIN TBL_LIBRARY_BRANCH
ON BOOK_COPIES_BRANCHID = LIBRARY_BRANCH_BRANCHID
WHERE BOOK_TITLE = "THE LOST TRIBE";

-- 3.RETRIEVE THE NAMES OF ALL BORROWERS WHO DO NOT HAVE ANY BOOKS CHECKED OUT.
SELECT BORROWER_BORROWERNAME AS BORROWER
FROM TBL_BORROWER 
LEFT JOIN TBL_BOOK_LOANS
ON BORROWER_CARDNO = BOOK_LOANS_CARDNO
WHERE BOOK_LOANS_BOOKID IS NULL;

-- 4.FOR EACH BOOK THAT IS LOANED OUT FROM THE "SHARPSTOWN" BRANCH AND WHOSE DUEDATE IS 2/3/18, RETRIEVE THE BOOK TITLE, THE BORROWER'S NAME, AND THE BORROWER'S ADDRESS. 
SELECT BOOK_TITLE,BORROWER_BORROWERNAME AS BORROWER_NAME,BORROWER_BORROWERADDRESS AS BORROWER_ADDRESS
FROM TBL_BORROWER 
JOIN TBL_BOOK_LOANS
ON BORROWER_CARDNO = BOOK_LOANS_CARDNO
JOIN TBL_LIBRARY_BRANCH
ON BOOK_LOANS_BRANCHID = LIBRARY_BRANCH_BRANCHID
JOIN TBL_BOOK
ON BOOK_LOANS_BOOKID = BOOK_BOOKID
WHERE LIBRARY_BRANCH_BRANCHNAME = "SHARPSTOWN" AND
BOOK_LOANS_DUEDATE = '2/3/18';

-- 5.FOR EACH LIBRARY BRANCH, RETRIEVE THE BRANCH NAME AND THE TOTAL NUMBER OF BOOKS LOANED OUT FROM THAT BRANCH.
SELECT LIBRARY_BRANCH_BRANCHNAME AS BRANCH_NAME,COUNT(*) AS TOTAL_BOOKS_LOANED_OUT
FROM TBL_LIBRARY_BRANCH
JOIN TBL_BOOK_LOANS
ON LIBRARY_BRANCH_BRANCHID = BOOK_LOANS_BRANCHID
GROUP BY LIBRARY_BRANCH_BRANCHNAME;

-- 6.RETRIEVE THE NAMES, ADDRESSES, AND NUMBER OF BOOKS CHECKED OUT FOR ALL BORROWERS WHO HAVE MORE THAN FIVE BOOKS CHECKED OUT.
SELECT BORROWER_BORROWERNAME AS BORROWER,BORROWER_BORROWERADDRESS AS ADDRESS,COUNT(*) AS TOTAL_BOOKS_CHECKED_OUT
FROM TBL_BORROWER
JOIN TBL_BOOK_LOANS
ON BORROWER_CARDNO = BOOK_LOANS_CARDNO
GROUP BY BORROWER_BORROWERNAME,BORROWER_BORROWERADDRESS
HAVING COUNT(*) > 5;

-- 7.FOR EACH BOOK AUTHORED BY "STEPHEN KING", RETRIEVE THE TITLE AND THE NUMBER OF COPIES OWNED BY THE LIBRARY BRANCH WHOSE NAME IS "CENTRAL".
SELECT BOOK_AUTHORS_AUTHORNAME AUTHOR,BOOK_TITLE,LIBRARY_BRANCH_BRANCHNAME AS BRANCH,BOOK_COPIES_NO_OF_COPIES AS NUMBER_OF_COPIES
FROM TBL_BOOK_AUTHORS 
JOIN TBL_BOOK
ON BOOK_AUTHORS_BOOKID = BOOK_BOOKID
JOIN TBL_BOOK_COPIES
ON BOOK_BOOKID = BOOK_COPIES_BOOKID
JOIN TBL_LIBRARY_BRANCH
ON BOOK_COPIES_BRANCHID = LIBRARY_BRANCH_BRANCHID
WHERE BOOK_AUTHORS_AUTHORNAME = "STEPHEN KING" AND LIBRARY_BRANCH_BRANCHNAME = "CENTRAL";
